[package]
name = "test2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.21"
ntex = { version = "0.5.21", features = ["tokio"] }
serde = "1.0.138"
serde_json = "1.0.82"
