[package]
name = "test2"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.21"
ntex = { version = "0.5.21", features = ["tokio"] }
serde = "1.0.138"
serde_json = "1.0.82"
utoipa = "1.1.0"
utoipa-swagger-ui = "1.1.0"
